steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['test']

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/neon-pad-338114/cloud-build', '--build-arg=JAR_FILE=target/build-artifact', '.']
images: ['gcr.io/neon-pad-338114/cloud-build']
