steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['test']
   
steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
   
steps:
 - name: gcr.io/cloud-builders/docker
   args: ['build', '-t', 'gcr.io/neon-pad-338114/cloud-spanner-build', '--build-arg=JAR_FILE=target/build-artifact', '.']
images: ['gcr.io/neon-pad-338114/cloud-spanner-build']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/neon-pad-338114/cloud-spanner-build']
